locales:
  bwi:
    name: Baniwa Keyboards
    description: >-
      Mobile OS keyboards for the Baniwa language from the Divvun group
      at UiT.
  en:
    name: Baniwa Keyboards
    description: >-
      Mobile OS keyboards for the Baniwa language from the Divvun group
      at UiT.
  nb:
    name: Baniwa tastatur
    description: Mobiltastatur for Baniwa fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
